/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "CO/CO_ODinterface.h" // TODO: Change back to "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00020192,
    .x1001_errorRegister = 0x00,
    .x1005_SYNC_COB_ID = 0x00000080,
    .x1006_communicationCyclePeriod = 0x000007D0,
    .x1016_consumerHeartbeatTime_sub0 = 0x01,
    .x1016_consumerHeartbeatTime = {0x000007D0},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .numberOfEntries = 0x04,
        .vendorID = 0x00000331,
        .productCode = 0x00000001,
        .revisionNumber = 0x00000100,
        .serialNumber = 0x00000001
    },
    .x1200_serverSDO_Parameter = {
        .numberOfEntries = 0x02,
        .COB_ID_ClientToServerReceiveSDO = 0x00000601,
        .COB_ID_ServerToClientTransmitSDO = 0x00000581
    },
    .x1400_receivePDO1Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000201,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1401_receivePDO2Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000301,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1402_receivePDO3Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000401,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1403_receivePDO4Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000501,
        .transmissionType = 0x01,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1600_receivePDO1Mapping_sub0 = 0x03,
    .x1600_receivePDO1Mapping = {0x60400010, 0x60600008, 0x607A0020},
    .x1601_receivePDO2Mapping_sub0 = 0x02,
    .x1601_receivePDO2Mapping = {0x607A0020, 0x60810020},
    .x1602_receivePDO3Mapping_sub0 = 0x03,
    .x1602_receivePDO3Mapping = {0x60400010, 0x60600008, 0x60FF0020},
    .x1603_receivePDO4Mapping_sub0 = 0x01,
    .x1603_receivePDO4Mapping = {0x607A0020},
    .x1800_transmitPDO1Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000181,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_transmitPDO2Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000281,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_transmitPDO3Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000381,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_transmitPDO4Parameter = {
        .highestSubIndexSupported = 0x06,
        .COB_IDUsedByPDO = 0x00000481,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_transmitPDO1Mapping_sub0 = 0x02,
    .x1A00_transmitPDO1Mapping = {0x60640020, 0x60410010},
    .x1A01_transmitPDO2Mapping_sub0 = 0x02,
    .x1A01_transmitPDO2Mapping = {0x60640020, 0x60410010},
    .x1A02_transmitPDO3Mapping_sub0 = 0x02,
    .x1A02_transmitPDO3Mapping = {0x606C0020, 0x60410010},
    .x1A03_transmitPDO4Mapping_sub0 = 0x02,
    .x1A03_transmitPDO4Mapping = {0x60640020, 0x60410010},
    .x2600_modbusEnable = 0x00,
    .x2601_driverEnable = 0x00,
    .x2604_weakMagneticAngle = 0x00,
    .x2609_DIR = 0x00,
    .x260A_electronicGearMolecules = 0x00,
    .x260B_electronicGearDenominator = 0x00,
    .x260C_incrementalPosition = 0x00,
    .x260E_ERROCode = 0x00,
    .x2612_systemTemperature = 0x00,
    .x2613_PWM = 0x00,
    .x2614_parameterSaveFlag = 0x00,
    .x2615_deviceAddress = 0x00,
    .x2618_staticMaxAllowOutput = 0x00,
    .x2619_specialFunction = 0x00,
    .x261C_CAN_CommunicationControlWord = 0x00,
    .x261D_maximumAllowableCurrent = 0x00,
    .x6040_controlword = 0x0000,
    .x6041_statusword = 0x0000,
    .x6060_modesOfOperation = 0,
    .x6064_positionActualValue = 0,
    .x606C_velocityActualValue = 0,
    .x6078_currentActualValue = 0,
    .x607A_targetPosition = 0,
    .x6081_profileVelocity = 0x00000000,
    .x6083_profileAcceleration = 0x00000000,
    .x60F9_velocityControlParameterSet = {
        .numberOfEntries = 0x02,
        .velocityRegulatorP_gain = 0,
        .velocityRegulatorI_gain = 0
    },
    .x60FB_positionControlParameterSet = {
        .numberOfEntries = 0x05,
        .positionRegulatorP_gain = 0,
        .positionRegulatorI_gain = 0,
        .positionRegulatorD_gain = 0,
        .velocityFeedForwardFactor = 0x0000,
        .accelerationFeedForwardFactor = 0x0000
    },
    .x60FF_targetVelocity = 0
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1005_SYNC_COB_ID;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_record_t o_1200_serverSDO_Parameter[3];
    OD_obj_record_t o_1400_receivePDO1Parameter[6];
    OD_obj_record_t o_1401_receivePDO2Parameter[6];
    OD_obj_record_t o_1402_receivePDO3Parameter[6];
    OD_obj_record_t o_1403_receivePDO4Parameter[6];
    OD_obj_array_t o_1600_receivePDO1Mapping;
    OD_obj_array_t o_1601_receivePDO2Mapping;
    OD_obj_array_t o_1602_receivePDO3Mapping;
    OD_obj_array_t o_1603_receivePDO4Mapping;
    OD_obj_record_t o_1800_transmitPDO1Parameter[6];
    OD_obj_record_t o_1801_transmitPDO2Parameter[6];
    OD_obj_record_t o_1802_transmitPDO3Parameter[6];
    OD_obj_record_t o_1803_transmitPDO4Parameter[6];
    OD_obj_array_t o_1A00_transmitPDO1Mapping;
    OD_obj_array_t o_1A01_transmitPDO2Mapping;
    OD_obj_array_t o_1A02_transmitPDO3Mapping;
    OD_obj_array_t o_1A03_transmitPDO4Mapping;
    OD_obj_var_t o_2600_modbusEnable;
    OD_obj_var_t o_2601_driverEnable;
    OD_obj_var_t o_2604_weakMagneticAngle;
    OD_obj_var_t o_2609_DIR;
    OD_obj_var_t o_260A_electronicGearMolecules;
    OD_obj_var_t o_260B_electronicGearDenominator;
    OD_obj_var_t o_260C_incrementalPosition;
    OD_obj_var_t o_260E_ERROCode;
    OD_obj_var_t o_2612_systemTemperature;
    OD_obj_var_t o_2613_PWM;
    OD_obj_var_t o_2614_parameterSaveFlag;
    OD_obj_var_t o_2615_deviceAddress;
    OD_obj_var_t o_2618_staticMaxAllowOutput;
    OD_obj_var_t o_2619_specialFunction;
    OD_obj_var_t o_261C_CAN_CommunicationControlWord;
    OD_obj_var_t o_261D_maximumAllowableCurrent;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_6078_currentActualValue;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_var_t o_6081_profileVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_record_t o_60F9_velocityControlParameterSet[3];
    OD_obj_record_t o_60FB_positionControlParameterSet[6];
    OD_obj_var_t o_60FF_targetVelocity;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1005_SYNC_COB_ID = {
        .dataOrig = &OD_RAM.x1005_SYNC_COB_ID,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_RAM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_RAM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_RAM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_RAM.x1018_identity.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.vendorID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1200_serverSDO_Parameter = {
        {
            .dataOrig = &OD_RAM.x1200_serverSDO_Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_serverSDO_Parameter.COB_ID_ClientToServerReceiveSDO,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_serverSDO_Parameter.COB_ID_ServerToClientTransmitSDO,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO1Parameter = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO2Parameter = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1402_receivePDO3Parameter = {
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1403_receivePDO4Parameter = {
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO1Mapping = {
        .dataOrig0 = &OD_RAM.x1600_receivePDO1Mapping_sub0,
        .dataOrig = &OD_RAM.x1600_receivePDO1Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1601_receivePDO2Mapping = {
        .dataOrig0 = &OD_RAM.x1601_receivePDO2Mapping_sub0,
        .dataOrig = &OD_RAM.x1601_receivePDO2Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1602_receivePDO3Mapping = {
        .dataOrig0 = &OD_RAM.x1602_receivePDO3Mapping_sub0,
        .dataOrig = &OD_RAM.x1602_receivePDO3Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1603_receivePDO4Mapping = {
        .dataOrig0 = &OD_RAM.x1603_receivePDO4Mapping_sub0,
        .dataOrig = &OD_RAM.x1603_receivePDO4Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1800_transmitPDO1Parameter = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_transmitPDO2Parameter = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_transmitPDO3Parameter = {
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_transmitPDO4Parameter = {
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.highestSubIndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_transmitPDO1Mapping = {
        .dataOrig0 = &OD_RAM.x1A00_transmitPDO1Mapping_sub0,
        .dataOrig = &OD_RAM.x1A00_transmitPDO1Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1A01_transmitPDO2Mapping = {
        .dataOrig0 = &OD_RAM.x1A01_transmitPDO2Mapping_sub0,
        .dataOrig = &OD_RAM.x1A01_transmitPDO2Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1A02_transmitPDO3Mapping = {
        .dataOrig0 = &OD_RAM.x1A02_transmitPDO3Mapping_sub0,
        .dataOrig = &OD_RAM.x1A02_transmitPDO3Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1A03_transmitPDO4Mapping = {
        .dataOrig0 = &OD_RAM.x1A03_transmitPDO4Mapping_sub0,
        .dataOrig = &OD_RAM.x1A03_transmitPDO4Mapping[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2600_modbusEnable = {
        .dataOrig = &OD_RAM.x2600_modbusEnable,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2601_driverEnable = {
        .dataOrig = &OD_RAM.x2601_driverEnable,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2604_weakMagneticAngle = {
        .dataOrig = &OD_RAM.x2604_weakMagneticAngle,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2609_DIR = {
        .dataOrig = &OD_RAM.x2609_DIR,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260A_electronicGearMolecules = {
        .dataOrig = &OD_RAM.x260A_electronicGearMolecules,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260B_electronicGearDenominator = {
        .dataOrig = &OD_RAM.x260B_electronicGearDenominator,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260C_incrementalPosition = {
        .dataOrig = &OD_RAM.x260C_incrementalPosition,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260E_ERROCode = {
        .dataOrig = &OD_RAM.x260E_ERROCode,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2612_systemTemperature = {
        .dataOrig = &OD_RAM.x2612_systemTemperature,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2613_PWM = {
        .dataOrig = &OD_RAM.x2613_PWM,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2614_parameterSaveFlag = {
        .dataOrig = &OD_RAM.x2614_parameterSaveFlag,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2615_deviceAddress = {
        .dataOrig = &OD_RAM.x2615_deviceAddress,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2618_staticMaxAllowOutput = {
        .dataOrig = &OD_RAM.x2618_staticMaxAllowOutput,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2619_specialFunction = {
        .dataOrig = &OD_RAM.x2619_specialFunction,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_261C_CAN_CommunicationControlWord = {
        .dataOrig = &OD_RAM.x261C_CAN_CommunicationControlWord,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_261D_maximumAllowableCurrent = {
        .dataOrig = &OD_RAM.x261D_maximumAllowableCurrent,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6040_controlword = {
        .dataOrig = &OD_RAM.x6040_controlword,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = &OD_RAM.x6041_statusword,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modesOfOperation = {
        .dataOrig = &OD_RAM.x6060_modesOfOperation,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6064_positionActualValue = {
        .dataOrig = &OD_RAM.x6064_positionActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocityActualValue = {
        .dataOrig = &OD_RAM.x606C_velocityActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6078_currentActualValue = {
        .dataOrig = &OD_RAM.x6078_currentActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_607A_targetPosition = {
        .dataOrig = &OD_RAM.x607A_targetPosition,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6081_profileVelocity = {
        .dataOrig = &OD_RAM.x6081_profileVelocity,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profileAcceleration = {
        .dataOrig = &OD_RAM.x6083_profileAcceleration,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60F9_velocityControlParameterSet = {
        {
            .dataOrig = &OD_RAM.x60F9_velocityControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60F9_velocityControlParameterSet.velocityRegulatorP_gain,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60F9_velocityControlParameterSet.velocityRegulatorI_gain,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_60FB_positionControlParameterSet = {
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.positionRegulatorP_gain,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.positionRegulatorI_gain,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.positionRegulatorD_gain,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.velocityFeedForwardFactor,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60FB_positionControlParameterSet.accelerationFeedForwardFactor,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_60FF_targetVelocity = {
        .dataOrig = &OD_RAM.x60FF_targetVelocity,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_SYNC_COB_ID, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1016, 0x02, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_serverSDO_Parameter, NULL},
    {0x1400, 0x06, ODT_REC, &ODObjs.o_1400_receivePDO1Parameter, NULL},
    {0x1401, 0x06, ODT_REC, &ODObjs.o_1401_receivePDO2Parameter, NULL},
    {0x1402, 0x06, ODT_REC, &ODObjs.o_1402_receivePDO3Parameter, NULL},
    {0x1403, 0x06, ODT_REC, &ODObjs.o_1403_receivePDO4Parameter, NULL},
    {0x1600, 0x04, ODT_ARR, &ODObjs.o_1600_receivePDO1Mapping, NULL},
    {0x1601, 0x03, ODT_ARR, &ODObjs.o_1601_receivePDO2Mapping, NULL},
    {0x1602, 0x04, ODT_ARR, &ODObjs.o_1602_receivePDO3Mapping, NULL},
    {0x1603, 0x02, ODT_ARR, &ODObjs.o_1603_receivePDO4Mapping, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO1Parameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO2Parameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_transmitPDO3Parameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_transmitPDO4Parameter, NULL},
    {0x1A00, 0x03, ODT_ARR, &ODObjs.o_1A00_transmitPDO1Mapping, NULL},
    {0x1A01, 0x03, ODT_ARR, &ODObjs.o_1A01_transmitPDO2Mapping, NULL},
    {0x1A02, 0x03, ODT_ARR, &ODObjs.o_1A02_transmitPDO3Mapping, NULL},
    {0x1A03, 0x03, ODT_ARR, &ODObjs.o_1A03_transmitPDO4Mapping, NULL},
    {0x2600, 0x01, ODT_VAR, &ODObjs.o_2600_modbusEnable, NULL},
    {0x2601, 0x01, ODT_VAR, &ODObjs.o_2601_driverEnable, NULL},
    {0x2604, 0x01, ODT_VAR, &ODObjs.o_2604_weakMagneticAngle, NULL},
    {0x2609, 0x01, ODT_VAR, &ODObjs.o_2609_DIR, NULL},
    {0x260A, 0x01, ODT_VAR, &ODObjs.o_260A_electronicGearMolecules, NULL},
    {0x260B, 0x01, ODT_VAR, &ODObjs.o_260B_electronicGearDenominator, NULL},
    {0x260C, 0x01, ODT_VAR, &ODObjs.o_260C_incrementalPosition, NULL},
    {0x260E, 0x01, ODT_VAR, &ODObjs.o_260E_ERROCode, NULL},
    {0x2612, 0x01, ODT_VAR, &ODObjs.o_2612_systemTemperature, NULL},
    {0x2613, 0x01, ODT_VAR, &ODObjs.o_2613_PWM, NULL},
    {0x2614, 0x01, ODT_VAR, &ODObjs.o_2614_parameterSaveFlag, NULL},
    {0x2615, 0x01, ODT_VAR, &ODObjs.o_2615_deviceAddress, NULL},
    {0x2618, 0x01, ODT_VAR, &ODObjs.o_2618_staticMaxAllowOutput, NULL},
    {0x2619, 0x01, ODT_VAR, &ODObjs.o_2619_specialFunction, NULL},
    {0x261C, 0x01, ODT_VAR, &ODObjs.o_261C_CAN_CommunicationControlWord, NULL},
    {0x261D, 0x01, ODT_VAR, &ODObjs.o_261D_maximumAllowableCurrent, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionActualValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x6078, 0x01, ODT_VAR, &ODObjs.o_6078_currentActualValue, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x60F9, 0x03, ODT_REC, &ODObjs.o_60F9_velocityControlParameterSet, NULL},
    {0x60FB, 0x06, ODT_REC, &ODObjs.o_60FB_positionControlParameterSet, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
