/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
// #include "CO_ODinterface.h"
#include "OD.h"

/*
#if CO_VERSION_MAJOR < 4
#warning This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif
*/

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/

void init_od_ram(OD_RAM_t *obj) {
    *obj = (OD_RAM_t){
        .x1000_deviceType = 0x00020192,
        .x1001_errorRegister = 0x00,
        .x1005_SYNC_COB_ID = 0x00000080,
        .x1006_communicationCyclePeriod = 0x000007D0,
        .x1016_consumerHeartbeatTime = {
            .numberOfEntries = 0x01,
            .consumerHeartbeatTime = 0x000007D0
        },
        .x1017_producerHeartbeatTime = 0x03E8,
        .x1018_identity = {
            .numberOfEntries = 0x04,
            .vendorID = 0x00000331,
            .productCode = 0x00000001,
            .revisionNumber = 0x00000100,
            .serialNumber = 0x00000001
        },
        .x1200_serverSDO_Parameter = {
            .numberOfEntries = 0x02,
            .COB_ID_ClientToServerReceiveSDO = 0x00000601,
            .COB_ID_ServerToClientTransmitSDO = 0x00000581
        },
        .x1201_additionalServerSDO1Parameter = {
            .numberOfEntries = 0x03,
            .COB_ID_ClientToServerReceiveSDO = 0x00000000,
            .COB_ID_ServerToClientTransmitSDO = 0x00000000,
            .nodeIDOfTheSDO_Client = 0x00
        },
        .x1280_clientSDO1Parameter = {
            .numberOfEntries = 0x03,
            .COB_ID_ClientToServerTransmitSDO = 0x00000000,
            .COB_ID_ServerToClientReceiveSDO = 0x00000000,
            .nodeIDOfTheSDO_Server = 0x00
        },
        .x1400_receivePDO1Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000201,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1401_receivePDO2Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000301,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1402_receivePDO3Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000401,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1403_receivePDO4Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000501,
            .transmissionType = 0x01,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1600_receivePDO1Mapping = {
            .numberOfEntries = 0x03,
            .PDO1MappingForAnApplicationObject1 = 0x60400010,
            .PDO1MappingForAnApplicationObject2 = 0x60600008,
            .PDO1MappingForAnApplicationObject3 = 0x607A0020
        },
        .x1601_receivePDO2Mapping = {
            .numberOfEntries = 0x02,
            .PDO2MappingForAnApplicationObject1 = 0x607A0020,
            .PDO2MappingForAnApplicationObject2 = 0x60810020
        },
        .x1602_receivePDO3Mapping = {
            .numberOfEntries = 0x03,
            .PDO3MappingForAnApplicationObject1 = 0x60400010,
            .PDO3MappingForAnApplicationObject2 = 0x60600008,
            .PDO3MappingForAnApplicationObject3 = 0x60FF0020
        },
        .x1603_receivePDO4Mapping = {
            .numberOfEntries = 0x01,
            .PDO4MappingForAnApplicationObject1 = 0x607A0020
        },
        .x1800_transmitPDO1Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000181,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1801_transmitPDO2Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000281,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1802_transmitPDO3Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000381,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1803_transmitPDO4Parameter = {
            .numberOfEntries = 0x06,
            .COB_IDUsedByPDO = 0x00000481,
            .transmissionType = 0xFF,
            .inhibitTime = 0x0001,
            .eventTimer = 0x0000,
            .SYNCStartValue = 0x00
        },
        .x1A00_transmitPDO1Mapping = {
            .numberOfEntries = 0x02,
            .PDO1MappingForaProcessDataVariable1 = 0x60640020,
            .PDO1MappingForaProcessDataVariable2 = 0x60410010
        },
        .x1A01_transmitPDO2Mapping = {
            .numberOfEntries = 0x02,
            .PDO2MappingForaProcessDataVariable1 = 0x60640020,
            .PDO2MappingForaProcessDataVariable2 = 0x60410010
        },
        .x1A02_transmitPDO3Mapping = {
            .numberOfEntries = 0x02,
            .PDO3MappingForaProcessDataVariable1 = 0x606C0020,
            .PDO3MappingForaProcessDataVariable2 = 0x60410010
        },
        .x1A03_transmitPDO4Mapping = {
            .numberOfEntries = 0x02,
            .PDO4MappingForaProcessDataVariable1 = 0x60640020,
            .PDO4MappingForaProcessDataVariable2 = 0x60410010
        },
        .x2600_modbusEnable = 0x00,
        .x2601_driverEnable = 0x00,
        .x2604_weakMagneticAngle = 0x00,
        .x2609_DIR = 0x00,
        .x260A_electronicGearMolecules = 0x00,
        .x260B_electronicGearDenominator = 0x00,
        .x260C_incrementalPosition = 0x00,
        .x260E_ERROCode = 0x00,
        .x2612_systemTemperature = 0x00,
        .x2613_PWM = 0x00,
        .x2614_parameterSaveFlag = 0x00,
        .x2615_deviceAddress = 0x00,
        .x2618_staticMaxAllowOutput = 0x00,
        .x2619_specialFunction = 0x00,
        .x261C_CAN_CommunicationControlWord = 0x00,
        .x261D_maximumAllowableCurrent = 0x00,
        .x6040_controlword = 0x0000,
        .x6041_statusword = 0x0000,
        .x6060_modesOfOperation = 0,
        .x6064_positionActualValue = 0,
        .x606C_velocityActualValue = 0,
        .x6078_currentActualValue = 0,
        .x607A_targetPosition = 0,
        .x6081_profileVelocity = 0x00000000,
        .x6083_profileAcceleration = 0x00000000,
        .x60F9_velocityControlParameterSet = {
            .numberOfEntries = 0x02,
            .velocityRegulatorP_gain = 0,
            .velocityRegulatorI_gain = 0
        },
        .x60FB_positionControlParameterSet = {
            .numberOfEntries = 0x05,
            .positionRegulatorP_gain = 0,
            .positionRegulatorI_gain = 0,
            .positionRegulatorD_gain = 0,
            .velocityFeedForwardFactor = 0x0000,
            .accelerationFeedForwardFactor = 0x0000
        },
        .x60FF_targetVelocity = 0
    };
}

/*
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00020192,
    .x1001_errorRegister = 0x00,
    .x1005_SYNC_COB_ID = 0x00000080,
    .x1006_communicationCyclePeriod = 0x000007D0,
    .x1016_consumerHeartbeatTime = {
        .numberOfEntries = 0x01,
        .consumerHeartbeatTime = 0x000007D0
    },
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .numberOfEntries = 0x04,
        .vendorID = 0x00000331,
        .productCode = 0x00000001,
        .revisionNumber = 0x00000100,
        .serialNumber = 0x00000001
    },
    .x1200_serverSDO_Parameter = {
        .numberOfEntries = 0x02,
        .COB_ID_ClientToServerReceiveSDO = 0x00000601,
        .COB_ID_ServerToClientTransmitSDO = 0x00000581
    },
    .x1201_additionalServerSDO1Parameter = {
        .numberOfEntries = 0x03,
        .COB_ID_ClientToServerReceiveSDO = 0x00000000,
        .COB_ID_ServerToClientTransmitSDO = 0x00000000,
        .nodeIDOfTheSDO_Client = 0x00
    },
    .x1280_clientSDO1Parameter = {
        .numberOfEntries = 0x03,
        .COB_ID_ClientToServerTransmitSDO = 0x00000000,
        .COB_ID_ServerToClientReceiveSDO = 0x00000000,
        .nodeIDOfTheSDO_Server = 0x00
    },
    .x1400_receivePDO1Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000201,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1401_receivePDO2Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000301,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1402_receivePDO3Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000401,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1403_receivePDO4Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000501,
        .transmissionType = 0x01,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1600_receivePDO1Mapping = {
        .numberOfEntries = 0x03,
        .PDO1MappingForAnApplicationObject1 = 0x60400010,
        .PDO1MappingForAnApplicationObject2 = 0x60600008,
        .PDO1MappingForAnApplicationObject3 = 0x607A0020
    },
    .x1601_receivePDO2Mapping = {
        .numberOfEntries = 0x02,
        .PDO2MappingForAnApplicationObject1 = 0x607A0020,
        .PDO2MappingForAnApplicationObject2 = 0x60810020
    },
    .x1602_receivePDO3Mapping = {
        .numberOfEntries = 0x03,
        .PDO3MappingForAnApplicationObject1 = 0x60400010,
        .PDO3MappingForAnApplicationObject2 = 0x60600008,
        .PDO3MappingForAnApplicationObject3 = 0x60FF0020
    },
    .x1603_receivePDO4Mapping = {
        .numberOfEntries = 0x01,
        .PDO4MappingForAnApplicationObject1 = 0x607A0020
    },
    .x1800_transmitPDO1Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000181,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_transmitPDO2Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000281,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_transmitPDO3Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000381,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_transmitPDO4Parameter = {
        .numberOfEntries = 0x06,
        .COB_IDUsedByPDO = 0x00000481,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0001,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_transmitPDO1Mapping = {
        .numberOfEntries = 0x02,
        .PDO1MappingForaProcessDataVariable1 = 0x60640020,
        .PDO1MappingForaProcessDataVariable2 = 0x60410010
    },
    .x1A01_transmitPDO2Mapping = {
        .numberOfEntries = 0x02,
        .PDO2MappingForaProcessDataVariable1 = 0x60640020,
        .PDO2MappingForaProcessDataVariable2 = 0x60410010
    },
    .x1A02_transmitPDO3Mapping = {
        .numberOfEntries = 0x02,
        .PDO3MappingForaProcessDataVariable1 = 0x606C0020,
        .PDO3MappingForaProcessDataVariable2 = 0x60410010
    },
    .x1A03_transmitPDO4Mapping = {
        .numberOfEntries = 0x02,
        .PDO4MappingForaProcessDataVariable1 = 0x60640020,
        .PDO4MappingForaProcessDataVariable2 = 0x60410010
    },
    .x2600_modbusEnable = 0x00,
    .x2601_driverEnable = 0x00,
    .x2604_weakMagneticAngle = 0x00,
    .x2609_DIR = 0x00,
    .x260A_electronicGearMolecules = 0x00,
    .x260B_electronicGearDenominator = 0x00,
    .x260C_incrementalPosition = 0x00,
    .x260E_ERROCode = 0x00,
    .x2612_systemTemperature = 0x00,
    .x2613_PWM = 0x00,
    .x2614_parameterSaveFlag = 0x00,
    .x2615_deviceAddress = 0x00,
    .x2618_staticMaxAllowOutput = 0x00,
    .x2619_specialFunction = 0x00,
    .x261C_CAN_CommunicationControlWord = 0x00,
    .x261D_maximumAllowableCurrent = 0x00,
    .x6040_controlword = 0x0000,
    .x6041_statusword = 0x0000,
    .x6060_modesOfOperation = 0,
    .x6064_positionActualValue = 0,
    .x606C_velocityActualValue = 0,
    .x6078_currentActualValue = 0,
    .x607A_targetPosition = 0,
    .x6081_profileVelocity = 0x00000000,
    .x6083_profileAcceleration = 0x00000000,
    .x60F9_velocityControlParameterSet = {
        .numberOfEntries = 0x02,
        .velocityRegulatorP_gain = 0,
        .velocityRegulatorI_gain = 0
    },
    .x60FB_positionControlParameterSet = {
        .numberOfEntries = 0x05,
        .positionRegulatorP_gain = 0,
        .positionRegulatorI_gain = 0,
        .positionRegulatorD_gain = 0,
        .velocityFeedForwardFactor = 0x0000,
        .accelerationFeedForwardFactor = 0x0000
    },
    .x60FF_targetVelocity = 0
};
*/

/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/

void init_odobjs(OD_RAM_t *obj, ODObjs_t* odobjs){
    *odobjs = (ODObjs_t){
        .o_1000_deviceType = {
            .dataOrig = &obj->x1000_deviceType,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        .o_1001_errorRegister = {
            .dataOrig = &obj->x1001_errorRegister,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        },
        .o_1005_SYNC_COB_ID = {
            .dataOrig = &obj->x1005_SYNC_COB_ID,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        .o_1006_communicationCyclePeriod = {
            .dataOrig = &obj->x1006_communicationCyclePeriod,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        .o_1016_consumerHeartbeatTime = {
            {
                .dataOrig = &obj->x1016_consumerHeartbeatTime.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1016_consumerHeartbeatTime.consumerHeartbeatTime,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1017_producerHeartbeatTime = {
            .dataOrig = &obj->x1017_producerHeartbeatTime,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        .o_1018_identity = {
            {
                .dataOrig = &obj->x1018_identity.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1018_identity.vendorID,
                .subIndex = 1,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1018_identity.productCode,
                .subIndex = 2,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1018_identity.revisionNumber,
                .subIndex = 3,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1018_identity.serialNumber,
                .subIndex = 4,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1200_serverSDO_Parameter = {
            {
                .dataOrig = &obj->x1200_serverSDO_Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1200_serverSDO_Parameter.COB_ID_ClientToServerReceiveSDO,
                .subIndex = 1,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1200_serverSDO_Parameter.COB_ID_ServerToClientTransmitSDO,
                .subIndex = 2,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1201_additionalServerSDO1Parameter = {
            {
                .dataOrig = &obj->x1201_additionalServerSDO1Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1201_additionalServerSDO1Parameter.COB_ID_ClientToServerReceiveSDO,
                .subIndex = 1,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1201_additionalServerSDO1Parameter.COB_ID_ServerToClientTransmitSDO,
                .subIndex = 2,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1201_additionalServerSDO1Parameter.nodeIDOfTheSDO_Client,
                .subIndex = 3,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            }
        },
        .o_1280_clientSDO1Parameter = {
            {
                .dataOrig = &obj->x1280_clientSDO1Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1280_clientSDO1Parameter.COB_ID_ClientToServerTransmitSDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1280_clientSDO1Parameter.COB_ID_ServerToClientReceiveSDO,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1280_clientSDO1Parameter.nodeIDOfTheSDO_Server,
                .subIndex = 3,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1400_receivePDO1Parameter = {
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1400_receivePDO1Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1401_receivePDO2Parameter = {
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1401_receivePDO2Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1402_receivePDO3Parameter = {
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1402_receivePDO3Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1403_receivePDO4Parameter = {
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1403_receivePDO4Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1600_receivePDO1Mapping = {
            {
                .dataOrig = &obj->x1600_receivePDO1Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject3,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1601_receivePDO2Mapping = {
            {
                .dataOrig = &obj->x1601_receivePDO2Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1601_receivePDO2Mapping.PDO2MappingForAnApplicationObject1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1601_receivePDO2Mapping.PDO2MappingForAnApplicationObject2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1602_receivePDO3Mapping = {
            {
                .dataOrig = &obj->x1602_receivePDO3Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject3,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1603_receivePDO4Mapping = {
            {
                .dataOrig = &obj->x1603_receivePDO4Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1603_receivePDO4Mapping.PDO4MappingForAnApplicationObject1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1800_transmitPDO1Parameter = {
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1800_transmitPDO1Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1801_transmitPDO2Parameter = {
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1801_transmitPDO2Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1802_transmitPDO3Parameter = {
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1802_transmitPDO3Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1803_transmitPDO4Parameter = {
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.COB_IDUsedByPDO,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.transmissionType,
                .subIndex = 2,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.inhibitTime,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.eventTimer,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x1803_transmitPDO4Parameter.SYNCStartValue,
                .subIndex = 6,
                .attribute = ODA_SDO_RW,
                .dataLength = 1
            }
        },
        .o_1A00_transmitPDO1Mapping = {
            {
                .dataOrig = &obj->x1A00_transmitPDO1Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1A00_transmitPDO1Mapping.PDO1MappingForaProcessDataVariable1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1A00_transmitPDO1Mapping.PDO1MappingForaProcessDataVariable2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1A01_transmitPDO2Mapping = {
            {
                .dataOrig = &obj->x1A01_transmitPDO2Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1A01_transmitPDO2Mapping.PDO2MappingForaProcessDataVariable1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1A01_transmitPDO2Mapping.PDO2MappingForaProcessDataVariable2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1A02_transmitPDO3Mapping = {
            {
                .dataOrig = &obj->x1A02_transmitPDO3Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1A02_transmitPDO3Mapping.PDO3MappingForaProcessDataVariable1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1A02_transmitPDO3Mapping.PDO3MappingForaProcessDataVariable2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_1A03_transmitPDO4Mapping = {
            {
                .dataOrig = &obj->x1A03_transmitPDO4Mapping.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x1A03_transmitPDO4Mapping.PDO4MappingForaProcessDataVariable1,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            },
            {
                .dataOrig = &obj->x1A03_transmitPDO4Mapping.PDO4MappingForaProcessDataVariable2,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
            }
        },
        .o_2600_modbusEnable = {
            .dataOrig = &obj->x2600_modbusEnable,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2601_driverEnable = {
            .dataOrig = &obj->x2601_driverEnable,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2604_weakMagneticAngle = {
            .dataOrig = &obj->x2604_weakMagneticAngle,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2609_DIR = {
            .dataOrig = &obj->x2609_DIR,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_260A_electronicGearMolecules = {
            .dataOrig = &obj->x260A_electronicGearMolecules,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 2
        },
        .o_260B_electronicGearDenominator = {
            .dataOrig = &obj->x260B_electronicGearDenominator,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 2
        },
        .o_260C_incrementalPosition = {
            .dataOrig = &obj->x260C_incrementalPosition,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_260E_ERROCode = {
            .dataOrig = &obj->x260E_ERROCode,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2612_systemTemperature = {
            .dataOrig = &obj->x2612_systemTemperature,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2613_PWM = {
            .dataOrig = &obj->x2613_PWM,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2614_parameterSaveFlag = {
            .dataOrig = &obj->x2614_parameterSaveFlag,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2615_deviceAddress = {
            .dataOrig = &obj->x2615_deviceAddress,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2618_staticMaxAllowOutput = {
            .dataOrig = &obj->x2618_staticMaxAllowOutput,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_2619_specialFunction = {
            .dataOrig = &obj->x2619_specialFunction,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_261C_CAN_CommunicationControlWord = {
            .dataOrig = &obj->x261C_CAN_CommunicationControlWord,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_261D_maximumAllowableCurrent = {
            .dataOrig = &obj->x261D_maximumAllowableCurrent,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_6040_controlword = {
            .dataOrig = &obj->x6040_controlword,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        .o_6041_statusword = {
            .dataOrig = &obj->x6041_statusword,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        .o_6060_modesOfOperation = {
            .dataOrig = &obj->x6060_modesOfOperation,
            .attribute = ODA_SDO_RW | ODA_TRPDO,
            .dataLength = 1
        },
        .o_6064_positionActualValue = {
            .dataOrig = &obj->x6064_positionActualValue,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        .o_606C_velocityActualValue = {
            .dataOrig = &obj->x606C_velocityActualValue,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        .o_6078_currentActualValue = {
            .dataOrig = &obj->x6078_currentActualValue,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        .o_607A_targetPosition = {
            .dataOrig = &obj->x607A_targetPosition,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        .o_6081_profileVelocity = {
            .dataOrig = &obj->x6081_profileVelocity,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        .o_6083_profileAcceleration = {
            .dataOrig = &obj->x6083_profileAcceleration,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        .o_60F9_velocityControlParameterSet = {
            {
                .dataOrig = &obj->x60F9_velocityControlParameterSet.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x60F9_velocityControlParameterSet.velocityRegulatorP_gain,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x60F9_velocityControlParameterSet.velocityRegulatorI_gain,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            }
        },
        .o_60FB_positionControlParameterSet = {
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.numberOfEntries,
                .subIndex = 0,
                .attribute = ODA_SDO_R,
                .dataLength = 1
            },
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorP_gain,
                .subIndex = 1,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorI_gain,
                .subIndex = 2,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorD_gain,
                .subIndex = 3,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.velocityFeedForwardFactor,
                .subIndex = 4,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            },
            {
                .dataOrig = &obj->x60FB_positionControlParameterSet.accelerationFeedForwardFactor,
                .subIndex = 5,
                .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                .dataLength = 2
            }
        },
        .o_60FF_targetVelocity = {
            .dataOrig = &obj->x60FF_targetVelocity,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        }
    };
}

/*
static const ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &obj->x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &obj->x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1005_SYNC_COB_ID = {
        .dataOrig = &obj->x1005_SYNC_COB_ID,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &obj->x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1016_consumerHeartbeatTime = {
        {
            .dataOrig = &obj->x1016_consumerHeartbeatTime.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1016_consumerHeartbeatTime.consumerHeartbeatTime,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &obj->x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &obj->x1018_identity.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1018_identity.vendorID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1200_serverSDO_Parameter = {
        {
            .dataOrig = &obj->x1200_serverSDO_Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1200_serverSDO_Parameter.COB_ID_ClientToServerReceiveSDO,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1200_serverSDO_Parameter.COB_ID_ServerToClientTransmitSDO,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1201_additionalServerSDO1Parameter = {
        {
            .dataOrig = &obj->x1201_additionalServerSDO1Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1201_additionalServerSDO1Parameter.COB_ID_ClientToServerReceiveSDO,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1201_additionalServerSDO1Parameter.COB_ID_ServerToClientTransmitSDO,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1201_additionalServerSDO1Parameter.nodeIDOfTheSDO_Client,
            .subIndex = 3,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        }
    },
    .o_1280_clientSDO1Parameter = {
        {
            .dataOrig = &obj->x1280_clientSDO1Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1280_clientSDO1Parameter.COB_ID_ClientToServerTransmitSDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1280_clientSDO1Parameter.COB_ID_ServerToClientReceiveSDO,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1280_clientSDO1Parameter.nodeIDOfTheSDO_Server,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_receivePDO1Parameter = {
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1400_receivePDO1Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO2Parameter = {
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1401_receivePDO2Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1402_receivePDO3Parameter = {
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1402_receivePDO3Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1403_receivePDO4Parameter = {
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1403_receivePDO4Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO1Mapping = {
        {
            .dataOrig = &obj->x1600_receivePDO1Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1600_receivePDO1Mapping.PDO1MappingForAnApplicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO2Mapping = {
        {
            .dataOrig = &obj->x1601_receivePDO2Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1601_receivePDO2Mapping.PDO2MappingForAnApplicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1601_receivePDO2Mapping.PDO2MappingForAnApplicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_receivePDO3Mapping = {
        {
            .dataOrig = &obj->x1602_receivePDO3Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1602_receivePDO3Mapping.PDO3MappingForAnApplicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_receivePDO4Mapping = {
        {
            .dataOrig = &obj->x1603_receivePDO4Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1603_receivePDO4Mapping.PDO4MappingForAnApplicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO1Parameter = {
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1800_transmitPDO1Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_transmitPDO2Parameter = {
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1801_transmitPDO2Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_transmitPDO3Parameter = {
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1802_transmitPDO3Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_transmitPDO4Parameter = {
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.COB_IDUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x1803_transmitPDO4Parameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_transmitPDO1Mapping = {
        {
            .dataOrig = &obj->x1A00_transmitPDO1Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1A00_transmitPDO1Mapping.PDO1MappingForaProcessDataVariable1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1A00_transmitPDO1Mapping.PDO1MappingForaProcessDataVariable2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_transmitPDO2Mapping = {
        {
            .dataOrig = &obj->x1A01_transmitPDO2Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1A01_transmitPDO2Mapping.PDO2MappingForaProcessDataVariable1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1A01_transmitPDO2Mapping.PDO2MappingForaProcessDataVariable2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_transmitPDO3Mapping = {
        {
            .dataOrig = &obj->x1A02_transmitPDO3Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1A02_transmitPDO3Mapping.PDO3MappingForaProcessDataVariable1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1A02_transmitPDO3Mapping.PDO3MappingForaProcessDataVariable2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_transmitPDO4Mapping = {
        {
            .dataOrig = &obj->x1A03_transmitPDO4Mapping.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x1A03_transmitPDO4Mapping.PDO4MappingForaProcessDataVariable1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &obj->x1A03_transmitPDO4Mapping.PDO4MappingForaProcessDataVariable2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2600_modbusEnable = {
        .dataOrig = &obj->x2600_modbusEnable,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2601_driverEnable = {
        .dataOrig = &obj->x2601_driverEnable,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2604_weakMagneticAngle = {
        .dataOrig = &obj->x2604_weakMagneticAngle,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2609_DIR = {
        .dataOrig = &obj->x2609_DIR,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260A_electronicGearMolecules = {
        .dataOrig = &obj->x260A_electronicGearMolecules,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260B_electronicGearDenominator = {
        .dataOrig = &obj->x260B_electronicGearDenominator,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260C_incrementalPosition = {
        .dataOrig = &obj->x260C_incrementalPosition,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_260E_ERROCode = {
        .dataOrig = &obj->x260E_ERROCode,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2612_systemTemperature = {
        .dataOrig = &obj->x2612_systemTemperature,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2613_PWM = {
        .dataOrig = &obj->x2613_PWM,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2614_parameterSaveFlag = {
        .dataOrig = &obj->x2614_parameterSaveFlag,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2615_deviceAddress = {
        .dataOrig = &obj->x2615_deviceAddress,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2618_staticMaxAllowOutput = {
        .dataOrig = &obj->x2618_staticMaxAllowOutput,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2619_specialFunction = {
        .dataOrig = &obj->x2619_specialFunction,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_261C_CAN_CommunicationControlWord = {
        .dataOrig = &obj->x261C_CAN_CommunicationControlWord,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_261D_maximumAllowableCurrent = {
        .dataOrig = &obj->x261D_maximumAllowableCurrent,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6040_controlword = {
        .dataOrig = &obj->x6040_controlword,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = &obj->x6041_statusword,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modesOfOperation = {
        .dataOrig = &obj->x6060_modesOfOperation,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6064_positionActualValue = {
        .dataOrig = &obj->x6064_positionActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocityActualValue = {
        .dataOrig = &obj->x606C_velocityActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6078_currentActualValue = {
        .dataOrig = &obj->x6078_currentActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_607A_targetPosition = {
        .dataOrig = &obj->x607A_targetPosition,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6081_profileVelocity = {
        .dataOrig = &obj->x6081_profileVelocity,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profileAcceleration = {
        .dataOrig = &obj->x6083_profileAcceleration,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60F9_velocityControlParameterSet = {
        {
            .dataOrig = &obj->x60F9_velocityControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x60F9_velocityControlParameterSet.velocityRegulatorP_gain,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x60F9_velocityControlParameterSet.velocityRegulatorI_gain,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_60FB_positionControlParameterSet = {
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorP_gain,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorI_gain,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.positionRegulatorD_gain,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.velocityFeedForwardFactor,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &obj->x60FB_positionControlParameterSet.accelerationFeedForwardFactor,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_60FF_targetVelocity = {
        .dataOrig = &obj->x60FF_targetVelocity,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    }
};
*/


/*******************************************************************************
    Object dictionary
*******************************************************************************/

/*
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_SYNC_COB_ID, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1016, 0x02, ODT_REC, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_serverSDO_Parameter, NULL},
    {0x1201, 0x04, ODT_REC, &ODObjs.o_1201_additionalServerSDO1Parameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_clientSDO1Parameter, NULL},
    {0x1400, 0x06, ODT_REC, &ODObjs.o_1400_receivePDO1Parameter, NULL},
    {0x1401, 0x06, ODT_REC, &ODObjs.o_1401_receivePDO2Parameter, NULL},
    {0x1402, 0x06, ODT_REC, &ODObjs.o_1402_receivePDO3Parameter, NULL},
    {0x1403, 0x06, ODT_REC, &ODObjs.o_1403_receivePDO4Parameter, NULL},
    {0x1600, 0x04, ODT_REC, &ODObjs.o_1600_receivePDO1Mapping, NULL},
    {0x1601, 0x03, ODT_REC, &ODObjs.o_1601_receivePDO2Mapping, NULL},
    {0x1602, 0x04, ODT_REC, &ODObjs.o_1602_receivePDO3Mapping, NULL},
    {0x1603, 0x02, ODT_REC, &ODObjs.o_1603_receivePDO4Mapping, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO1Parameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO2Parameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_transmitPDO3Parameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_transmitPDO4Parameter, NULL},
    {0x1A00, 0x03, ODT_REC, &ODObjs.o_1A00_transmitPDO1Mapping, NULL},
    {0x1A01, 0x03, ODT_REC, &ODObjs.o_1A01_transmitPDO2Mapping, NULL},
    {0x1A02, 0x03, ODT_REC, &ODObjs.o_1A02_transmitPDO3Mapping, NULL},
    {0x1A03, 0x03, ODT_REC, &ODObjs.o_1A03_transmitPDO4Mapping, NULL},
    {0x2600, 0x01, ODT_VAR, &ODObjs.o_2600_modbusEnable, NULL},
    {0x2601, 0x01, ODT_VAR, &ODObjs.o_2601_driverEnable, NULL},
    {0x2604, 0x01, ODT_VAR, &ODObjs.o_2604_weakMagneticAngle, NULL},
    {0x2609, 0x01, ODT_VAR, &ODObjs.o_2609_DIR, NULL},
    {0x260A, 0x01, ODT_VAR, &ODObjs.o_260A_electronicGearMolecules, NULL},
    {0x260B, 0x01, ODT_VAR, &ODObjs.o_260B_electronicGearDenominator, NULL},
    {0x260C, 0x01, ODT_VAR, &ODObjs.o_260C_incrementalPosition, NULL},
    {0x260E, 0x01, ODT_VAR, &ODObjs.o_260E_ERROCode, NULL},
    {0x2612, 0x01, ODT_VAR, &ODObjs.o_2612_systemTemperature, NULL},
    {0x2613, 0x01, ODT_VAR, &ODObjs.o_2613_PWM, NULL},
    {0x2614, 0x01, ODT_VAR, &ODObjs.o_2614_parameterSaveFlag, NULL},
    {0x2615, 0x01, ODT_VAR, &ODObjs.o_2615_deviceAddress, NULL},
    {0x2618, 0x01, ODT_VAR, &ODObjs.o_2618_staticMaxAllowOutput, NULL},
    {0x2619, 0x01, ODT_VAR, &ODObjs.o_2619_specialFunction, NULL},
    {0x261C, 0x01, ODT_VAR, &ODObjs.o_261C_CAN_CommunicationControlWord, NULL},
    {0x261D, 0x01, ODT_VAR, &ODObjs.o_261D_maximumAllowableCurrent, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionActualValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x6078, 0x01, ODT_VAR, &ODObjs.o_6078_currentActualValue, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x60F9, 0x03, ODT_REC, &ODObjs.o_60F9_velocityControlParameterSet, NULL},
    {0x60FB, 0x06, ODT_REC, &ODObjs.o_60FB_positionControlParameterSet, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
*/

