/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: YZ_MOTOR.eds
        File Version: 1

        Created:      7/14/2025 8:01:00 PM
        Created By:   CANFestival
        Modified:     7/14/2025 8:01:00 PM
        Modified By:  CANFestival

    Device Info:
        Vendor Name:  CANFestival
        Vendor ID:    0x00000331
        Product Name: my_motor
        Product ID:   0x00000001

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H

#include <stdint.h>

/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 2
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4

/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    struct {
        uint8_t numberOfEntries;
        uint32_t consumerHeartbeatTime;
    } x1016_consumerHeartbeatTime;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
    } x1200_serverSDO_Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
        uint8_t nodeIDOfTheSDO_Client;
    } x1201_additionalServerSDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerTransmitSDO;
        uint32_t COB_ID_ServerToClientReceiveSDO;
        uint8_t nodeIDOfTheSDO_Server;
    } x1280_clientSDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1400_receivePDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1401_receivePDO2Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1402_receivePDO3Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1403_receivePDO4Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForAnApplicationObject1;
        uint32_t PDO1MappingForAnApplicationObject2;
        uint32_t PDO1MappingForAnApplicationObject3;
    } x1600_receivePDO1Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForAnApplicationObject1;
        uint32_t PDO2MappingForAnApplicationObject2;
    } x1601_receivePDO2Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForAnApplicationObject1;
        uint32_t PDO3MappingForAnApplicationObject2;
        uint32_t PDO3MappingForAnApplicationObject3;
    } x1602_receivePDO3Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForAnApplicationObject1;
    } x1603_receivePDO4Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_transmitPDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_transmitPDO2Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_transmitPDO3Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_transmitPDO4Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForaProcessDataVariable1;
        uint32_t PDO1MappingForaProcessDataVariable2;
    } x1A00_transmitPDO1Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForaProcessDataVariable1;
        uint32_t PDO2MappingForaProcessDataVariable2;
    } x1A01_transmitPDO2Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForaProcessDataVariable1;
        uint32_t PDO3MappingForaProcessDataVariable2;
    } x1A02_transmitPDO3Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForaProcessDataVariable1;
        uint32_t PDO4MappingForaProcessDataVariable2;
    } x1A03_transmitPDO4Mapping;
    uint8_t x2600_modbusEnable;
    uint8_t x2601_driverEnable;
    uint8_t x2604_weakMagneticAngle;
    uint8_t x2609_DIR;
    uint8_t x260A_electronicGearMolecules;
    uint8_t x260B_electronicGearDenominator;
    uint8_t x260C_incrementalPosition;
    uint8_t x260E_ERROCode;
    uint8_t x2612_systemTemperature;
    uint8_t x2613_PWM;
    uint8_t x2614_parameterSaveFlag;
    uint8_t x2615_deviceAddress;
    uint8_t x2618_staticMaxAllowOutput;
    uint8_t x2619_specialFunction;
    uint8_t x261C_CAN_CommunicationControlWord;
    uint8_t x261D_maximumAllowableCurrent;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int32_t x6064_positionActualValue;
    int32_t x606C_velocityActualValue;
    int16_t x6078_currentActualValue;
    int32_t x607A_targetPosition;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    struct {
        uint8_t numberOfEntries;
        int16_t velocityRegulatorP_gain;
        int16_t velocityRegulatorI_gain;
    } x60F9_velocityControlParameterSet;
    struct {
        uint8_t numberOfEntries;
        int16_t positionRegulatorP_gain;
        int16_t positionRegulatorI_gain;
        int16_t positionRegulatorD_gain;
        uint16_t velocityFeedForwardFactor;
        uint16_t accelerationFeedForwardFactor;
    } x60FB_positionControlParameterSet;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
//extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
// extern OD_ATTR_OD OD_t *OD;

typedef uint32_t OD_size_t; /**< Variable of type OD_size_t contains data length in bytes of OD variable */
typedef uint8_t OD_attr_t; 

typedef enum {
    ODA_SDO_R = 0x01U,  /**< SDO server may read from the variable */
    ODA_SDO_W = 0x02U,  /**< SDO server may write to the variable */
    ODA_SDO_RW = 0x03U, /**< SDO server may read from or write to the variable */
    ODA_TPDO = 0x04U,   /**< Variable is mappable into TPDO (can be read) */
    ODA_RPDO = 0x08U,   /**< Variable is mappable into RPDO (can be written) */
    ODA_TRPDO = 0x0CU,  /**< Variable is mappable into TPDO or RPDO */
    ODA_TSRDO = 0x10U,  /**< Variable is mappable into transmitting SRDO */
    ODA_RSRDO = 0x20U,  /**< Variable is mappable into receiving SRDO */
    ODA_TRSRDO = 0x30U, /**< Variable is mappable into tx or rx SRDO */
    ODA_MB = 0x40U,     /**< Variable is multi-byte ((u)int16_t to (u)int64_t) */
    ODA_STR = 0x80U     /**< Shorter value, than specified variable size, may be written to the variable. SDO write will
                           fill remaining memory with zeroes. Attribute is used for VISIBLE_STRING and UNICODE_STRING. */
} OD_attributes_t;

typedef struct {
    void* dataOrig;       /**< Pointer to data */
    OD_attr_t attribute;  /**< Attribute bitfield, see @ref OD_attributes_t */
    OD_size_t dataLength; /**< Data length in bytes */
} OD_obj_var_t;

typedef struct {
    void* dataOrig;       /**< Pointer to data */
    uint8_t subIndex;     /**< Sub index of element. */
    OD_attr_t attribute;  /**< Attribute bitfield, see @ref OD_attributes_t */
    OD_size_t dataLength; /**< Data length in bytes */
} OD_obj_record_t;

void init_od_ram(OD_RAM_t *obj);

typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1005_SYNC_COB_ID;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_record_t o_1016_consumerHeartbeatTime[2];
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_record_t o_1200_serverSDO_Parameter[3];
    OD_obj_record_t o_1201_additionalServerSDO1Parameter[4];
    OD_obj_record_t o_1280_clientSDO1Parameter[4];
    OD_obj_record_t o_1400_receivePDO1Parameter[6];
    OD_obj_record_t o_1401_receivePDO2Parameter[6];
    OD_obj_record_t o_1402_receivePDO3Parameter[6];
    OD_obj_record_t o_1403_receivePDO4Parameter[6];
    OD_obj_record_t o_1600_receivePDO1Mapping[4];
    OD_obj_record_t o_1601_receivePDO2Mapping[3];
    OD_obj_record_t o_1602_receivePDO3Mapping[4];
    OD_obj_record_t o_1603_receivePDO4Mapping[2];
    OD_obj_record_t o_1800_transmitPDO1Parameter[6];
    OD_obj_record_t o_1801_transmitPDO2Parameter[6];
    OD_obj_record_t o_1802_transmitPDO3Parameter[6];
    OD_obj_record_t o_1803_transmitPDO4Parameter[6];
    OD_obj_record_t o_1A00_transmitPDO1Mapping[3];
    OD_obj_record_t o_1A01_transmitPDO2Mapping[3];
    OD_obj_record_t o_1A02_transmitPDO3Mapping[3];
    OD_obj_record_t o_1A03_transmitPDO4Mapping[3];
    OD_obj_var_t o_2600_modbusEnable;
    OD_obj_var_t o_2601_driverEnable;
    OD_obj_var_t o_2604_weakMagneticAngle;
    OD_obj_var_t o_2609_DIR;
    OD_obj_var_t o_260A_electronicGearMolecules;
    OD_obj_var_t o_260B_electronicGearDenominator;
    OD_obj_var_t o_260C_incrementalPosition;
    OD_obj_var_t o_260E_ERROCode;
    OD_obj_var_t o_2612_systemTemperature;
    OD_obj_var_t o_2613_PWM;
    OD_obj_var_t o_2614_parameterSaveFlag;
    OD_obj_var_t o_2615_deviceAddress;
    OD_obj_var_t o_2618_staticMaxAllowOutput;
    OD_obj_var_t o_2619_specialFunction;
    OD_obj_var_t o_261C_CAN_CommunicationControlWord;
    OD_obj_var_t o_261D_maximumAllowableCurrent;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_6078_currentActualValue;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_var_t o_6081_profileVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_record_t o_60F9_velocityControlParameterSet[3];
    OD_obj_record_t o_60FB_positionControlParameterSet[6];
    OD_obj_var_t o_60FF_targetVelocity;
} ODObjs_t;

void init_odobjs(OD_RAM_t *obj, ODObjs_t* odobjs);

/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
/*
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1005 &OD->list[2]
#define OD_ENTRY_H1006 &OD->list[3]
#define OD_ENTRY_H1016 &OD->list[4]
#define OD_ENTRY_H1017 &OD->list[5]
#define OD_ENTRY_H1018 &OD->list[6]
#define OD_ENTRY_H1200 &OD->list[7]
#define OD_ENTRY_H1201 &OD->list[8]
#define OD_ENTRY_H1280 &OD->list[9]
#define OD_ENTRY_H1400 &OD->list[10]
#define OD_ENTRY_H1401 &OD->list[11]
#define OD_ENTRY_H1402 &OD->list[12]
#define OD_ENTRY_H1403 &OD->list[13]
#define OD_ENTRY_H1600 &OD->list[14]
#define OD_ENTRY_H1601 &OD->list[15]
#define OD_ENTRY_H1602 &OD->list[16]
#define OD_ENTRY_H1603 &OD->list[17]
#define OD_ENTRY_H1800 &OD->list[18]
#define OD_ENTRY_H1801 &OD->list[19]
#define OD_ENTRY_H1802 &OD->list[20]
#define OD_ENTRY_H1803 &OD->list[21]
#define OD_ENTRY_H1A00 &OD->list[22]
#define OD_ENTRY_H1A01 &OD->list[23]
#define OD_ENTRY_H1A02 &OD->list[24]
#define OD_ENTRY_H1A03 &OD->list[25]
#define OD_ENTRY_H2600 &OD->list[26]
#define OD_ENTRY_H2601 &OD->list[27]
#define OD_ENTRY_H2604 &OD->list[28]
#define OD_ENTRY_H2609 &OD->list[29]
#define OD_ENTRY_H260A &OD->list[30]
#define OD_ENTRY_H260B &OD->list[31]
#define OD_ENTRY_H260C &OD->list[32]
#define OD_ENTRY_H260E &OD->list[33]
#define OD_ENTRY_H2612 &OD->list[34]
#define OD_ENTRY_H2613 &OD->list[35]
#define OD_ENTRY_H2614 &OD->list[36]
#define OD_ENTRY_H2615 &OD->list[37]
#define OD_ENTRY_H2618 &OD->list[38]
#define OD_ENTRY_H2619 &OD->list[39]
#define OD_ENTRY_H261C &OD->list[40]
#define OD_ENTRY_H261D &OD->list[41]
#define OD_ENTRY_H6040 &OD->list[42]
#define OD_ENTRY_H6041 &OD->list[43]
#define OD_ENTRY_H6060 &OD->list[44]
#define OD_ENTRY_H6064 &OD->list[45]
#define OD_ENTRY_H606C &OD->list[46]
#define OD_ENTRY_H6078 &OD->list[47]
#define OD_ENTRY_H607A &OD->list[48]
#define OD_ENTRY_H6081 &OD->list[49]
#define OD_ENTRY_H6083 &OD->list[50]
#define OD_ENTRY_H60F9 &OD->list[51]
#define OD_ENTRY_H60FB &OD->list[52]
#define OD_ENTRY_H60FF &OD->list[53]
*/

/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/

/*
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1005_SYNC_COB_ID &OD->list[2]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[3]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[4]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[5]
#define OD_ENTRY_H1018_identity &OD->list[6]
#define OD_ENTRY_H1200_serverSDO_Parameter &OD->list[7]
#define OD_ENTRY_H1201_additionalServerSDO1Parameter &OD->list[8]
#define OD_ENTRY_H1280_clientSDO1Parameter &OD->list[9]
#define OD_ENTRY_H1400_receivePDO1Parameter &OD->list[10]
#define OD_ENTRY_H1401_receivePDO2Parameter &OD->list[11]
#define OD_ENTRY_H1402_receivePDO3Parameter &OD->list[12]
#define OD_ENTRY_H1403_receivePDO4Parameter &OD->list[13]
#define OD_ENTRY_H1600_receivePDO1Mapping &OD->list[14]
#define OD_ENTRY_H1601_receivePDO2Mapping &OD->list[15]
#define OD_ENTRY_H1602_receivePDO3Mapping &OD->list[16]
#define OD_ENTRY_H1603_receivePDO4Mapping &OD->list[17]
#define OD_ENTRY_H1800_transmitPDO1Parameter &OD->list[18]
#define OD_ENTRY_H1801_transmitPDO2Parameter &OD->list[19]
#define OD_ENTRY_H1802_transmitPDO3Parameter &OD->list[20]
#define OD_ENTRY_H1803_transmitPDO4Parameter &OD->list[21]
#define OD_ENTRY_H1A00_transmitPDO1Mapping &OD->list[22]
#define OD_ENTRY_H1A01_transmitPDO2Mapping &OD->list[23]
#define OD_ENTRY_H1A02_transmitPDO3Mapping &OD->list[24]
#define OD_ENTRY_H1A03_transmitPDO4Mapping &OD->list[25]
#define OD_ENTRY_H2600_modbusEnable &OD->list[26]
#define OD_ENTRY_H2601_driverEnable &OD->list[27]
#define OD_ENTRY_H2604_weakMagneticAngle &OD->list[28]
#define OD_ENTRY_H2609_DIR &OD->list[29]
#define OD_ENTRY_H260A_electronicGearMolecules &OD->list[30]
#define OD_ENTRY_H260B_electronicGearDenominator &OD->list[31]
#define OD_ENTRY_H260C_incrementalPosition &OD->list[32]
#define OD_ENTRY_H260E_ERROCode &OD->list[33]
#define OD_ENTRY_H2612_systemTemperature &OD->list[34]
#define OD_ENTRY_H2613_PWM &OD->list[35]
#define OD_ENTRY_H2614_parameterSaveFlag &OD->list[36]
#define OD_ENTRY_H2615_deviceAddress &OD->list[37]
#define OD_ENTRY_H2618_staticMaxAllowOutput &OD->list[38]
#define OD_ENTRY_H2619_specialFunction &OD->list[39]
#define OD_ENTRY_H261C_CAN_CommunicationControlWord &OD->list[40]
#define OD_ENTRY_H261D_maximumAllowableCurrent &OD->list[41]
#define OD_ENTRY_H6040_controlword &OD->list[42]
#define OD_ENTRY_H6041_statusword &OD->list[43]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[44]
#define OD_ENTRY_H6064_positionActualValue &OD->list[45]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[46]
#define OD_ENTRY_H6078_currentActualValue &OD->list[47]
#define OD_ENTRY_H607A_targetPosition &OD->list[48]
#define OD_ENTRY_H6081_profileVelocity &OD->list[49]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[50]
#define OD_ENTRY_H60F9_velocityControlParameterSet &OD->list[51]
#define OD_ENTRY_H60FB_positionControlParameterSet &OD->list[52]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[53]
*/

/*******************************************************************************
    OD config structure
*******************************************************************************/
/*
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}

#endif
*/

#endif /* OD_H */
