/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: YZ_MOTOR.eds
        File Version: 1

        Created:      7/14/2025 8:01:00 PM
        Created By:   CANFestival
        Modified:     7/14/2025 8:01:00 PM
        Modified By:  CANFestival

    Device Info:
        Vendor Name:  CANFestival
        Vendor ID:    0x00000331
        Product Name: my_motor
        Product ID:   0x00000001

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H

#include <stdint.h>

/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 2
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4

/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    struct {
        uint8_t numberOfEntries;
        uint32_t consumerHeartbeatTime;
    } x1016_consumerHeartbeatTime;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
    } x1200_serverSDO_Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
        uint8_t nodeIDOfTheSDO_Client;
    } x1201_additionalServerSDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerTransmitSDO;
        uint32_t COB_ID_ServerToClientReceiveSDO;
        uint8_t nodeIDOfTheSDO_Server;
    } x1280_clientSDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1400_receivePDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1401_receivePDO2Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1402_receivePDO3Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1403_receivePDO4Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForAnApplicationObject1;
        uint32_t PDO1MappingForAnApplicationObject2;
        uint32_t PDO1MappingForAnApplicationObject3;
    } x1600_receivePDO1Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForAnApplicationObject1;
        uint32_t PDO2MappingForAnApplicationObject2;
    } x1601_receivePDO2Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForAnApplicationObject1;
        uint32_t PDO3MappingForAnApplicationObject2;
        uint32_t PDO3MappingForAnApplicationObject3;
    } x1602_receivePDO3Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForAnApplicationObject1;
    } x1603_receivePDO4Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_transmitPDO1Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_transmitPDO2Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_transmitPDO3Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_transmitPDO4Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForaProcessDataVariable1;
        uint32_t PDO1MappingForaProcessDataVariable2;
    } x1A00_transmitPDO1Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForaProcessDataVariable1;
        uint32_t PDO2MappingForaProcessDataVariable2;
    } x1A01_transmitPDO2Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForaProcessDataVariable1;
        uint32_t PDO3MappingForaProcessDataVariable2;
    } x1A02_transmitPDO3Mapping;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForaProcessDataVariable1;
        uint32_t PDO4MappingForaProcessDataVariable2;
    } x1A03_transmitPDO4Mapping;
    uint8_t x2600_modbusEnable;
    uint8_t x2601_driverEnable;
    uint8_t x2604_weakMagneticAngle;
    uint8_t x2609_DIR;
    uint8_t x260A_electronicGearMolecules;
    uint8_t x260B_electronicGearDenominator;
    uint8_t x260C_incrementalPosition;
    uint8_t x260E_ERROCode;
    uint8_t x2612_systemTemperature;
    uint8_t x2613_PWM;
    uint8_t x2614_parameterSaveFlag;
    uint8_t x2615_deviceAddress;
    uint8_t x2618_staticMaxAllowOutput;
    uint8_t x2619_specialFunction;
    uint8_t x261C_CAN_CommunicationControlWord;
    uint8_t x261D_maximumAllowableCurrent;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int32_t x6064_positionActualValue;
    int32_t x606C_velocityActualValue;
    int16_t x6078_currentActualValue;
    int32_t x607A_targetPosition;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    struct {
        uint8_t numberOfEntries;
        int16_t velocityRegulatorP_gain;
        int16_t velocityRegulatorI_gain;
    } x60F9_velocityControlParameterSet;
    struct {
        uint8_t numberOfEntries;
        int16_t positionRegulatorP_gain;
        int16_t positionRegulatorI_gain;
        int16_t positionRegulatorD_gain;
        uint16_t velocityFeedForwardFactor;
        uint16_t accelerationFeedForwardFactor;
    } x60FB_positionControlParameterSet;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

/*
#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
//extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
// extern OD_ATTR_OD OD_t *OD;
*/
//typedef uint32_t OD_size_t; /**< Variable of type OD_size_t contains data length in bytes of OD variable */

//typedef uint8_t OD_attr_t; 

//typedef enum {
//    ODA_SDO_R = 0x01U,  /**< SDO server may read from the variable */
//    ODA_SDO_W = 0x02U,  /**< SDO server may write to the variable */
//     ODA_SDO_RW = 0x03U, /**< SDO server may read from or write to the variable */
//     ODA_TPDO = 0x04U,   /**< Variable is mappable into TPDO (can be read) */
//     ODA_RPDO = 0x08U,   /**< Variable is mappable into RPDO (can be written) */
//     ODA_TRPDO = 0x0CU,  /**< Variable is mappable into TPDO or RPDO */
//     ODA_TSRDO = 0x10U,  /**< Variable is mappable into transmitting SRDO */
//     ODA_RSRDO = 0x20U,  /**< Variable is mappable into receiving SRDO */
//     ODA_TRSRDO = 0x30U, /**< Variable is mappable into tx or rx SRDO */
//     ODA_MB = 0x40U,     /**< Variable is multi-byte ((u)int16_t to (u)int64_t) */
//     ODA_STR = 0x80U     /**< Shorter value, than specified variable size, may be written to the variable. SDO write will
//                            fill remaining memory with zeroes. Attribute is used for VISIBLE_STRING and UNICODE_STRING. */
// } OD_attributes_t;

// typedef struct {
//     void* dataOrig;       /**< Pointer to data */
//     OD_attr_t attribute;  /**< Attribute bitfield, see @ref OD_attributes_t */
//     OD_size_t dataLength; /**< Data length in bytes */
// } OD_obj_var_t;

// typedef struct {
//     void* dataOrig;       /**< Pointer to data */
//     uint8_t subIndex;     /**< Sub index of element. */
//     OD_attr_t attribute;  /**< Attribute bitfield, see @ref OD_attributes_t */
//     OD_size_t dataLength; /**< Data length in bytes */
// } OD_obj_record_t;

void init_od_ram(OD_RAM_t *obj);

// typedef struct {
//     OD_obj_var_t o_1000_deviceType;
//     OD_obj_var_t o_1001_errorRegister;
//     OD_obj_var_t o_1005_SYNC_COB_ID;
//     OD_obj_var_t o_1006_communicationCyclePeriod;
//     OD_obj_record_t o_1016_consumerHeartbeatTime[2];
//     OD_obj_var_t o_1017_producerHeartbeatTime;
//     OD_obj_record_t o_1018_identity[5];
//     OD_obj_record_t o_1200_serverSDO_Parameter[3];
//     OD_obj_record_t o_1201_additionalServerSDO1Parameter[4];
//     OD_obj_record_t o_1280_clientSDO1Parameter[4];
//     OD_obj_record_t o_1400_receivePDO1Parameter[6];
//     OD_obj_record_t o_1401_receivePDO2Parameter[6];
//     OD_obj_record_t o_1402_receivePDO3Parameter[6];
//     OD_obj_record_t o_1403_receivePDO4Parameter[6];
//     OD_obj_record_t o_1600_receivePDO1Mapping[4];
//     OD_obj_record_t o_1601_receivePDO2Mapping[3];
//     OD_obj_record_t o_1602_receivePDO3Mapping[4];
//     OD_obj_record_t o_1603_receivePDO4Mapping[2];
//     OD_obj_record_t o_1800_transmitPDO1Parameter[6];
//     OD_obj_record_t o_1801_transmitPDO2Parameter[6];
//     OD_obj_record_t o_1802_transmitPDO3Parameter[6];
//     OD_obj_record_t o_1803_transmitPDO4Parameter[6];
//     OD_obj_record_t o_1A00_transmitPDO1Mapping[3];
//     OD_obj_record_t o_1A01_transmitPDO2Mapping[3];
//     OD_obj_record_t o_1A02_transmitPDO3Mapping[3];
//     OD_obj_record_t o_1A03_transmitPDO4Mapping[3];
//     OD_obj_var_t o_2600_modbusEnable;
//     OD_obj_var_t o_2601_driverEnable;
//     OD_obj_var_t o_2604_weakMagneticAngle;
//     OD_obj_var_t o_2609_DIR;
//     OD_obj_var_t o_260A_electronicGearMolecules;
//     OD_obj_var_t o_260B_electronicGearDenominator;
//     OD_obj_var_t o_260C_incrementalPosition;
//     OD_obj_var_t o_260E_ERROCode;
//     OD_obj_var_t o_2612_systemTemperature;
//     OD_obj_var_t o_2613_PWM;
//     OD_obj_var_t o_2614_parameterSaveFlag;
//     OD_obj_var_t o_2615_deviceAddress;
//     OD_obj_var_t o_2618_staticMaxAllowOutput;
//     OD_obj_var_t o_2619_specialFunction;
//     OD_obj_var_t o_261C_CAN_CommunicationControlWord;
//     OD_obj_var_t o_261D_maximumAllowableCurrent;
//     OD_obj_var_t o_6040_controlword;
//     OD_obj_var_t o_6041_statusword;
//     OD_obj_var_t o_6060_modesOfOperation;
//     OD_obj_var_t o_6064_positionActualValue;
//     OD_obj_var_t o_606C_velocityActualValue;
//     OD_obj_var_t o_6078_currentActualValue;
//     OD_obj_var_t o_607A_targetPosition;
//     OD_obj_var_t o_6081_profileVelocity;
//     OD_obj_var_t o_6083_profileAcceleration;
//     OD_obj_record_t o_60F9_velocityControlParameterSet[3];
//     OD_obj_record_t o_60FB_positionControlParameterSet[6];
//     OD_obj_var_t o_60FF_targetVelocity;
// } ODObjs_t;

// void init_odobjs(OD_RAM_t *obj, ODObjs_t* odobjs);


#endif /* OD_H */
