/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: YZ_MOTOR.eds
        File Version: 1

        Created:      7/14/2025 8:01:00 PM
        Created By:   CANFestival
        Modified:     7/14/2025 8:01:00 PM
        Modified By:  CANFestival

    Device Info:
        Vendor Name:  CANFestival
        Vendor ID:    0x00000331
        Product Name: my_motor
        Product ID:   0x00000001

        Description:
*******************************************************************************/

#ifndef OD_H

#define OD_H

#include <stdint.h>

/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 2
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4

/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/

/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct
{
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t consumerHeartbeatTime;
    } x1016_consumerHeartbeatTime;
    uint16_t x1017_producerHeartbeatTime;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
    } x1200_serverSDO_Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
        uint8_t nodeIDOfTheSDO_Client;
    } x1201_additionalServerSDO1Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerTransmitSDO;
        uint32_t COB_ID_ServerToClientReceiveSDO;
        uint8_t nodeIDOfTheSDO_Server;
    } x1280_clientSDO1Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1400_receivePDO1Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1401_receivePDO2Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1402_receivePDO3Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1403_receivePDO4Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForAnApplicationObject1;
        uint32_t PDO1MappingForAnApplicationObject2;
        uint32_t PDO1MappingForAnApplicationObject3;
    } x1600_receivePDO1Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForAnApplicationObject1;
        uint32_t PDO2MappingForAnApplicationObject2;
    } x1601_receivePDO2Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForAnApplicationObject1;
        uint32_t PDO3MappingForAnApplicationObject2;
        uint32_t PDO3MappingForAnApplicationObject3;
    } x1602_receivePDO3Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForAnApplicationObject1;
    } x1603_receivePDO4Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_transmitPDO1Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_transmitPDO2Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_transmitPDO3Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_transmitPDO4Parameter;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO1MappingForaProcessDataVariable1;
        uint32_t PDO1MappingForaProcessDataVariable2;
    } x1A00_transmitPDO1Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO2MappingForaProcessDataVariable1;
        uint32_t PDO2MappingForaProcessDataVariable2;
    } x1A01_transmitPDO2Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO3MappingForaProcessDataVariable1;
        uint32_t PDO3MappingForaProcessDataVariable2;
    } x1A02_transmitPDO3Mapping;
    struct
    {
        uint8_t numberOfEntries;
        uint32_t PDO4MappingForaProcessDataVariable1;
        uint32_t PDO4MappingForaProcessDataVariable2;
    } x1A03_transmitPDO4Mapping;
    uint8_t x2600_modbusEnable;
    uint8_t x2601_driverEnable;
    uint8_t x2604_weakMagneticAngle;
    uint8_t x2609_DIR;
    uint16_t x260A_electronicGearMolecules; // do not know why 8 bits. The manual sa1ys it is 16 bits
    uint8_t x260B_electronicGearDenominator;
    uint8_t x260C_incrementalPosition;
    uint8_t x260E_ERROCode;
    uint8_t x2612_systemTemperature;
    uint8_t x2613_PWM;
    uint8_t x2614_parameterSaveFlag;
    uint8_t x2615_deviceAddress;
    uint8_t x2618_staticMaxAllowOutput;
    uint8_t x2619_specialFunction;
    uint8_t x261C_CAN_CommunicationControlWord;
    uint8_t x261D_maximumAllowableCurrent;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int32_t x6064_positionActualValue;
    int32_t x606C_velocityActualValue;
    int16_t x6078_currentActualValue;
    int32_t x607A_targetPosition;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    struct
    {
        uint8_t numberOfEntries;
        int16_t velocityRegulatorP_gain;
        int16_t velocityRegulatorI_gain;
    } x60F9_velocityControlParameterSet;
    struct
    {
        uint8_t numberOfEntries;
        int16_t positionRegulatorP_gain;
        int16_t positionRegulatorI_gain;
        int16_t positionRegulatorD_gain;
        uint16_t velocityFeedForwardFactor;
        uint16_t accelerationFeedForwardFactor;
    } x60FB_positionControlParameterSet;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

void init_od_ram(OD_RAM_t *obj);

#endif // OD_H