/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: YZ_MOTOR.eds
        File Version: 1

        Created:      2/28/2021 9:38:00 PM
        Created By:   CANFestival
        Modified:     2/28/2021 9:38:00 PM
        Modified By:  CANFestival

    Device Info:
        Vendor Name:  CANFestival
        Vendor ID:    0x00000331
        Product Name: 
        Product ID:   0x00000001

        Description:  
*******************************************************************************/
#include "CO/CO_ODinterface.h"

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1016 1
#define OD_CNT_ARR_1600 3
#define OD_CNT_ARR_1601 2
#define OD_CNT_ARR_1602 3
#define OD_CNT_ARR_1603 1
#define OD_CNT_ARR_1A00 2
#define OD_CNT_ARR_1A01 2
#define OD_CNT_ARR_1A02 2
#define OD_CNT_ARR_1A03 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
    } x1200_serverSDO_Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1400_receivePDO1Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1401_receivePDO2Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1402_receivePDO3Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1403_receivePDO4Parameter;
    uint8_t x1600_receivePDO1Mapping_sub0;
    uint32_t x1600_receivePDO1Mapping[OD_CNT_ARR_1600];
    uint8_t x1601_receivePDO2Mapping_sub0;
    uint32_t x1601_receivePDO2Mapping[OD_CNT_ARR_1601];
    uint8_t x1602_receivePDO3Mapping_sub0;
    uint32_t x1602_receivePDO3Mapping[OD_CNT_ARR_1602];
    uint8_t x1603_receivePDO4Mapping_sub0;
    uint32_t x1603_receivePDO4Mapping[OD_CNT_ARR_1603];
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_transmitPDO1Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_transmitPDO2Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_transmitPDO3Parameter;
    struct {
        uint8_t highestSubIndexSupported;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_transmitPDO4Parameter;
    uint8_t x1A00_transmitPDO1Mapping_sub0;
    uint32_t x1A00_transmitPDO1Mapping[OD_CNT_ARR_1A00];
    uint8_t x1A01_transmitPDO2Mapping_sub0;
    uint32_t x1A01_transmitPDO2Mapping[OD_CNT_ARR_1A01];
    uint8_t x1A02_transmitPDO3Mapping_sub0;
    uint32_t x1A02_transmitPDO3Mapping[OD_CNT_ARR_1A02];
    uint8_t x1A03_transmitPDO4Mapping_sub0;
    uint32_t x1A03_transmitPDO4Mapping[OD_CNT_ARR_1A03];
    uint8_t x2600_modbusEnable;
    uint8_t x2601_driverEnable;
    uint8_t x2604_weakMagneticAngle;
    uint8_t x2609_DIR;
    uint8_t x260A_electronicGearMolecules;
    uint8_t x260B_electronicGearDenominator;
    uint8_t x260C_incrementalPosition;
    uint8_t x260E_ERROCode;
    uint8_t x2612_systemTemperature;
    uint8_t x2613_PWM;
    uint8_t x2614_parameterSaveFlag;
    uint8_t x2615_deviceAddress;
    uint8_t x2618_staticMaxAllowOutput;
    uint8_t x2619_specialFunction;
    uint8_t x261C_CAN_CommunicationControlWord;
    uint8_t x261D_maximumAllowableCurrent;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int32_t x6064_positionActualValue;
    int32_t x606C_velocityActualValue;
    int16_t x6078_currentActualValue;
    int32_t x607A_targetPosition;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    struct {
        uint8_t numberOfEntries;
        int16_t velocityRegulatorP_gain;
        int16_t velocityRegulatorI_gain;
    } x60F9_velocityControlParameterSet;
    struct {
        uint8_t numberOfEntries;
        int16_t positionRegulatorP_gain;
        int16_t positionRegulatorI_gain;
        int16_t positionRegulatorD_gain;
        uint16_t velocityFeedForwardFactor;
        uint16_t accelerationFeedForwardFactor;
    } x60FB_positionControlParameterSet;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

void init_od_ram(OD_RAM_t *obj);

/*
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1005_SYNC_COB_ID;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_record_t o_1200_serverSDO_Parameter[3];
    OD_obj_record_t o_1400_receivePDO1Parameter[6];
    OD_obj_record_t o_1401_receivePDO2Parameter[6];
    OD_obj_record_t o_1402_receivePDO3Parameter[6];
    OD_obj_record_t o_1403_receivePDO4Parameter[6];
    OD_obj_array_t o_1600_receivePDO1Mapping;
    OD_obj_array_t o_1601_receivePDO2Mapping;
    OD_obj_array_t o_1602_receivePDO3Mapping;
    OD_obj_array_t o_1603_receivePDO4Mapping;
    OD_obj_record_t o_1800_transmitPDO1Parameter[6];
    OD_obj_record_t o_1801_transmitPDO2Parameter[6];
    OD_obj_record_t o_1802_transmitPDO3Parameter[6];
    OD_obj_record_t o_1803_transmitPDO4Parameter[6];
    OD_obj_array_t o_1A00_transmitPDO1Mapping;
    OD_obj_array_t o_1A01_transmitPDO2Mapping;
    OD_obj_array_t o_1A02_transmitPDO3Mapping;
    OD_obj_array_t o_1A03_transmitPDO4Mapping;
    OD_obj_var_t o_2600_modbusEnable;
    OD_obj_var_t o_2601_driverEnable;
    OD_obj_var_t o_2604_weakMagneticAngle;
    OD_obj_var_t o_2609_DIR;
    OD_obj_var_t o_260A_electronicGearMolecules;
    OD_obj_var_t o_260B_electronicGearDenominator;
    OD_obj_var_t o_260C_incrementalPosition;
    OD_obj_var_t o_260E_ERROCode;
    OD_obj_var_t o_2612_systemTemperature;
    OD_obj_var_t o_2613_PWM;
    OD_obj_var_t o_2614_parameterSaveFlag;
    OD_obj_var_t o_2615_deviceAddress;
    OD_obj_var_t o_2618_staticMaxAllowOutput;
    OD_obj_var_t o_2619_specialFunction;
    OD_obj_var_t o_261C_CAN_CommunicationControlWord;
    OD_obj_var_t o_261D_maximumAllowableCurrent;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_6078_currentActualValue;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_var_t o_6081_profileVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_record_t o_60F9_velocityControlParameterSet[3];
    OD_obj_record_t o_60FB_positionControlParameterSet[6];
    OD_obj_var_t o_60FF_targetVelocity;
} ODObjs_t;

void init_odobjs(OD_RAM_t *obj, ODObjs_t* odobjs);
*/
#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
// extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
// extern OD_ATTR_OD OD_t *OD;

/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
